/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Int_comparison_exp:{
		_eq:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"Int",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	String_comparison_exp:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_iregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_like:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nilike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:true
		},
		_niregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nlike:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nregex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nsimilar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_regex:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_similar:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup:{
		meetup_comments:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comments_aggregate:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_users:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_users_aggregate:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	meetup_aggregate_fields:{
		count:{
			columns:{
				type:"meetup_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	meetup_bool_exp:{
		_and:{
			type:"meetup_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"meetup_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"meetup_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		datetime:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		image_url:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments:{
			type:"meetup_comment_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users:{
			type:"meetup_user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_aggregate_fields:{
		count:{
			columns:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	meetup_comment_aggregate_order_by:{
		avg:{
			type:"meetup_comment_avg_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"meetup_comment_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"meetup_comment_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev:{
			type:"meetup_comment_stddev_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_pop:{
			type:"meetup_comment_stddev_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_samp:{
			type:"meetup_comment_stddev_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		sum:{
			type:"meetup_comment_sum_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_pop:{
			type:"meetup_comment_var_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_samp:{
			type:"meetup_comment_var_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		variance:{
			type:"meetup_comment_variance_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_arr_rel_insert_input:{
		data:{
			type:"meetup_comment_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		},
		on_conflict:{
			type:"meetup_comment_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_avg_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_bool_exp:{
		_and:{
			type:"meetup_comment_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"meetup_comment_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"meetup_comment_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup:{
			type:"meetup_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_constraint: "enum",
	meetup_comment_inc_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_insert_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup:{
			type:"meetup_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_max_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_min_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_on_conflict:{
		constraint:{
			type:"meetup_comment_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"meetup_comment_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"meetup_comment_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup:{
			type:"meetup_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_pk_columns_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	meetup_comment_select_column: "enum",
	meetup_comment_set_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		text:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_stddev_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_stddev_pop_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_stddev_samp_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_sum_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_update_column: "enum",
	meetup_comment_var_pop_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_var_samp_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_comment_variance_order_by:{
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_constraint: "enum",
	meetup_inc_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_insert_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		datetime:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		image_url:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments:{
			type:"meetup_comment_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users:{
			type:"meetup_user_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_obj_rel_insert_input:{
		data:{
			type:"meetup_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"meetup_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_on_conflict:{
		constraint:{
			type:"meetup_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"meetup_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"meetup_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_order_by:{
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		datetime:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		image_url:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments_aggregate:{
			type:"meetup_comment_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users_aggregate:{
			type:"meetup_user_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_pk_columns_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	meetup_select_column: "enum",
	meetup_set_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		datetime:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		image_url:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_update_column: "enum",
	meetup_user_aggregate_fields:{
		count:{
			columns:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	meetup_user_aggregate_order_by:{
		avg:{
			type:"meetup_user_avg_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		count:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		max:{
			type:"meetup_user_max_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		min:{
			type:"meetup_user_min_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev:{
			type:"meetup_user_stddev_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_pop:{
			type:"meetup_user_stddev_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		stddev_samp:{
			type:"meetup_user_stddev_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		sum:{
			type:"meetup_user_sum_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_pop:{
			type:"meetup_user_var_pop_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		var_samp:{
			type:"meetup_user_var_samp_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		variance:{
			type:"meetup_user_variance_order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_arr_rel_insert_input:{
		data:{
			type:"meetup_user_insert_input",
			array:true,
			arrayRequired:true,
			required:true
		},
		on_conflict:{
			type:"meetup_user_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_avg_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_bool_exp:{
		_and:{
			type:"meetup_user_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"meetup_user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"meetup_user_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		meetup:{
			type:"meetup_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_constraint: "enum",
	meetup_user_inc_input:{
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_insert_input:{
		meetup:{
			type:"meetup_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_obj_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_max_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_min_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_on_conflict:{
		constraint:{
			type:"meetup_user_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"meetup_user_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"meetup_user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_order_by:{
		meetup:{
			type:"meetup_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user:{
			type:"user_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_pk_columns_input:{
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	meetup_user_select_column: "enum",
	meetup_user_set_input:{
		meetup_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_stddev_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_stddev_pop_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_stddev_samp_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_sum_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_update_column: "enum",
	meetup_user_var_pop_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_var_samp_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	meetup_user_variance_order_by:{
		meetup_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	mutation_root:{
		delete_meetup:{
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_meetup_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_meetup_comment:{
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_meetup_comment_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_meetup_user:{
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_meetup_user_by_pk:{
			meetup_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_user:{
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_user_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		insert_meetup:{
			objects:{
				type:"meetup_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"meetup_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_meetup_comment:{
			objects:{
				type:"meetup_comment_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"meetup_comment_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_meetup_comment_one:{
			object:{
				type:"meetup_comment_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"meetup_comment_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_meetup_one:{
			object:{
				type:"meetup_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"meetup_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_meetup_user:{
			objects:{
				type:"meetup_user_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"meetup_user_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_meetup_user_one:{
			object:{
				type:"meetup_user_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"meetup_user_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_user:{
			objects:{
				type:"user_insert_input",
				array:true,
				arrayRequired:true,
				required:true
			},
			on_conflict:{
				type:"user_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		insert_user_one:{
			object:{
				type:"user_insert_input",
				array:false,
				arrayRequired:false,
				required:true
			},
			on_conflict:{
				type:"user_on_conflict",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		update_meetup:{
			_inc:{
				type:"meetup_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_meetup_by_pk:{
			_inc:{
				type:"meetup_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"meetup_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_meetup_comment:{
			_inc:{
				type:"meetup_comment_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_comment_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_meetup_comment_by_pk:{
			_inc:{
				type:"meetup_comment_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_comment_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"meetup_comment_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_meetup_user:{
			_inc:{
				type:"meetup_user_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_user_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_meetup_user_by_pk:{
			_inc:{
				type:"meetup_user_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"meetup_user_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"meetup_user_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_user:{
			_inc:{
				type:"user_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"user_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_user_by_pk:{
			_inc:{
				type:"user_inc_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			_set:{
				type:"user_set_input",
				array:false,
				arrayRequired:false,
				required:false
			},
			pk_columns:{
				type:"user_pk_columns_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	order_by: "enum",
	query_root:{
		meetup:{
			distinct_on:{
				type:"meetup_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_aggregate:{
			distinct_on:{
				type:"meetup_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		meetup_comment:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comment_aggregate:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comment_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		meetup_user:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_user_aggregate:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_user_by_pk:{
			meetup_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		user:{
			distinct_on:{
				type:"user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user_aggregate:{
			distinct_on:{
				type:"user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	subscription_root:{
		meetup:{
			distinct_on:{
				type:"meetup_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_aggregate:{
			distinct_on:{
				type:"meetup_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		meetup_comment:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comment_aggregate:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comment_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		meetup_user:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_user_aggregate:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_user_by_pk:{
			meetup_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			},
			user_id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		user:{
			distinct_on:{
				type:"user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user_aggregate:{
			distinct_on:{
				type:"user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user_by_pk:{
			id:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	timestamptz: "String",
	timestamptz_comparison_exp:{
		_eq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		},
		_is_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"timestamptz",
			array:true,
			arrayRequired:false,
			required:true
		}
	},
	user:{
		meetup_comments:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_comments_aggregate:{
			distinct_on:{
				type:"meetup_comment_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_comment_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_comment_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_users:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		meetup_users_aggregate:{
			distinct_on:{
				type:"meetup_user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			order_by:{
				type:"meetup_user_order_by",
				array:true,
				arrayRequired:false,
				required:true
			},
			where:{
				type:"meetup_user_bool_exp",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	user_aggregate_fields:{
		count:{
			columns:{
				type:"user_select_column",
				array:true,
				arrayRequired:false,
				required:true
			},
			distinct:{
				type:"Boolean",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	user_bool_exp:{
		_and:{
			type:"user_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		_not:{
			type:"user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"user_bool_exp",
			array:true,
			arrayRequired:false,
			required:true
		},
		created_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments:{
			type:"meetup_comment_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users:{
			type:"meetup_user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz_comparison_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_constraint: "enum",
	user_inc_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_insert_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments:{
			type:"meetup_comment_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users:{
			type:"meetup_user_arr_rel_insert_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_obj_rel_insert_input:{
		data:{
			type:"user_insert_input",
			array:false,
			arrayRequired:false,
			required:true
		},
		on_conflict:{
			type:"user_on_conflict",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_on_conflict:{
		constraint:{
			type:"user_constraint",
			array:false,
			arrayRequired:false,
			required:true
		},
		update_columns:{
			type:"user_update_column",
			array:true,
			arrayRequired:true,
			required:true
		},
		where:{
			type:"user_bool_exp",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_order_by:{
		created_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_comments_aggregate:{
			type:"meetup_comment_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		meetup_users_aggregate:{
			type:"meetup_user_aggregate_order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"order_by",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_pk_columns_input:{
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	user_select_column: "enum",
	user_set_input:{
		created_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		updated_at:{
			type:"timestamptz",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	user_update_column: "enum"
}

export const ReturnTypes: Record<string,any> = {
	cached:{
		ttl:"Int",
		refresh:"Boolean"
	},
	meetup:{
		created_at:"timestamptz",
		datetime:"timestamptz",
		description:"String",
		id:"Int",
		image_url:"String",
		location:"String",
		meetup_comments:"meetup_comment",
		meetup_comments_aggregate:"meetup_comment_aggregate",
		meetup_users:"meetup_user",
		meetup_users_aggregate:"meetup_user_aggregate",
		name:"String",
		updated_at:"timestamptz"
	},
	meetup_aggregate:{
		aggregate:"meetup_aggregate_fields",
		nodes:"meetup"
	},
	meetup_aggregate_fields:{
		avg:"meetup_avg_fields",
		count:"Int",
		max:"meetup_max_fields",
		min:"meetup_min_fields",
		stddev:"meetup_stddev_fields",
		stddev_pop:"meetup_stddev_pop_fields",
		stddev_samp:"meetup_stddev_samp_fields",
		sum:"meetup_sum_fields",
		var_pop:"meetup_var_pop_fields",
		var_samp:"meetup_var_samp_fields",
		variance:"meetup_variance_fields"
	},
	meetup_avg_fields:{
		id:"Float"
	},
	meetup_comment:{
		id:"Int",
		meetup:"meetup",
		meetup_id:"Int",
		text:"String",
		user:"user",
		user_id:"Int"
	},
	meetup_comment_aggregate:{
		aggregate:"meetup_comment_aggregate_fields",
		nodes:"meetup_comment"
	},
	meetup_comment_aggregate_fields:{
		avg:"meetup_comment_avg_fields",
		count:"Int",
		max:"meetup_comment_max_fields",
		min:"meetup_comment_min_fields",
		stddev:"meetup_comment_stddev_fields",
		stddev_pop:"meetup_comment_stddev_pop_fields",
		stddev_samp:"meetup_comment_stddev_samp_fields",
		sum:"meetup_comment_sum_fields",
		var_pop:"meetup_comment_var_pop_fields",
		var_samp:"meetup_comment_var_samp_fields",
		variance:"meetup_comment_variance_fields"
	},
	meetup_comment_avg_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_max_fields:{
		id:"Int",
		meetup_id:"Int",
		text:"String",
		user_id:"Int"
	},
	meetup_comment_min_fields:{
		id:"Int",
		meetup_id:"Int",
		text:"String",
		user_id:"Int"
	},
	meetup_comment_mutation_response:{
		affected_rows:"Int",
		returning:"meetup_comment"
	},
	meetup_comment_stddev_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_stddev_pop_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_stddev_samp_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_sum_fields:{
		id:"Int",
		meetup_id:"Int",
		user_id:"Int"
	},
	meetup_comment_var_pop_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_var_samp_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_comment_variance_fields:{
		id:"Float",
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_max_fields:{
		created_at:"timestamptz",
		datetime:"timestamptz",
		description:"String",
		id:"Int",
		image_url:"String",
		location:"String",
		name:"String",
		updated_at:"timestamptz"
	},
	meetup_min_fields:{
		created_at:"timestamptz",
		datetime:"timestamptz",
		description:"String",
		id:"Int",
		image_url:"String",
		location:"String",
		name:"String",
		updated_at:"timestamptz"
	},
	meetup_mutation_response:{
		affected_rows:"Int",
		returning:"meetup"
	},
	meetup_stddev_fields:{
		id:"Float"
	},
	meetup_stddev_pop_fields:{
		id:"Float"
	},
	meetup_stddev_samp_fields:{
		id:"Float"
	},
	meetup_sum_fields:{
		id:"Int"
	},
	meetup_user:{
		meetup:"meetup",
		meetup_id:"Int",
		user:"user",
		user_id:"Int"
	},
	meetup_user_aggregate:{
		aggregate:"meetup_user_aggregate_fields",
		nodes:"meetup_user"
	},
	meetup_user_aggregate_fields:{
		avg:"meetup_user_avg_fields",
		count:"Int",
		max:"meetup_user_max_fields",
		min:"meetup_user_min_fields",
		stddev:"meetup_user_stddev_fields",
		stddev_pop:"meetup_user_stddev_pop_fields",
		stddev_samp:"meetup_user_stddev_samp_fields",
		sum:"meetup_user_sum_fields",
		var_pop:"meetup_user_var_pop_fields",
		var_samp:"meetup_user_var_samp_fields",
		variance:"meetup_user_variance_fields"
	},
	meetup_user_avg_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_max_fields:{
		meetup_id:"Int",
		user_id:"Int"
	},
	meetup_user_min_fields:{
		meetup_id:"Int",
		user_id:"Int"
	},
	meetup_user_mutation_response:{
		affected_rows:"Int",
		returning:"meetup_user"
	},
	meetup_user_stddev_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_stddev_pop_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_stddev_samp_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_sum_fields:{
		meetup_id:"Int",
		user_id:"Int"
	},
	meetup_user_var_pop_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_var_samp_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_user_variance_fields:{
		meetup_id:"Float",
		user_id:"Float"
	},
	meetup_var_pop_fields:{
		id:"Float"
	},
	meetup_var_samp_fields:{
		id:"Float"
	},
	meetup_variance_fields:{
		id:"Float"
	},
	mutation_root:{
		delete_meetup:"meetup_mutation_response",
		delete_meetup_by_pk:"meetup",
		delete_meetup_comment:"meetup_comment_mutation_response",
		delete_meetup_comment_by_pk:"meetup_comment",
		delete_meetup_user:"meetup_user_mutation_response",
		delete_meetup_user_by_pk:"meetup_user",
		delete_user:"user_mutation_response",
		delete_user_by_pk:"user",
		insert_meetup:"meetup_mutation_response",
		insert_meetup_comment:"meetup_comment_mutation_response",
		insert_meetup_comment_one:"meetup_comment",
		insert_meetup_one:"meetup",
		insert_meetup_user:"meetup_user_mutation_response",
		insert_meetup_user_one:"meetup_user",
		insert_user:"user_mutation_response",
		insert_user_one:"user",
		update_meetup:"meetup_mutation_response",
		update_meetup_by_pk:"meetup",
		update_meetup_comment:"meetup_comment_mutation_response",
		update_meetup_comment_by_pk:"meetup_comment",
		update_meetup_user:"meetup_user_mutation_response",
		update_meetup_user_by_pk:"meetup_user",
		update_user:"user_mutation_response",
		update_user_by_pk:"user"
	},
	query_root:{
		meetup:"meetup",
		meetup_aggregate:"meetup_aggregate",
		meetup_by_pk:"meetup",
		meetup_comment:"meetup_comment",
		meetup_comment_aggregate:"meetup_comment_aggregate",
		meetup_comment_by_pk:"meetup_comment",
		meetup_user:"meetup_user",
		meetup_user_aggregate:"meetup_user_aggregate",
		meetup_user_by_pk:"meetup_user",
		user:"user",
		user_aggregate:"user_aggregate",
		user_by_pk:"user"
	},
	subscription_root:{
		meetup:"meetup",
		meetup_aggregate:"meetup_aggregate",
		meetup_by_pk:"meetup",
		meetup_comment:"meetup_comment",
		meetup_comment_aggregate:"meetup_comment_aggregate",
		meetup_comment_by_pk:"meetup_comment",
		meetup_user:"meetup_user",
		meetup_user_aggregate:"meetup_user_aggregate",
		meetup_user_by_pk:"meetup_user",
		user:"user",
		user_aggregate:"user_aggregate",
		user_by_pk:"user"
	},
	user:{
		created_at:"timestamptz",
		email:"String",
		id:"Int",
		meetup_comments:"meetup_comment",
		meetup_comments_aggregate:"meetup_comment_aggregate",
		meetup_users:"meetup_user",
		meetup_users_aggregate:"meetup_user_aggregate",
		password:"String",
		updated_at:"timestamptz"
	},
	user_aggregate:{
		aggregate:"user_aggregate_fields",
		nodes:"user"
	},
	user_aggregate_fields:{
		avg:"user_avg_fields",
		count:"Int",
		max:"user_max_fields",
		min:"user_min_fields",
		stddev:"user_stddev_fields",
		stddev_pop:"user_stddev_pop_fields",
		stddev_samp:"user_stddev_samp_fields",
		sum:"user_sum_fields",
		var_pop:"user_var_pop_fields",
		var_samp:"user_var_samp_fields",
		variance:"user_variance_fields"
	},
	user_avg_fields:{
		id:"Float"
	},
	user_max_fields:{
		created_at:"timestamptz",
		email:"String",
		id:"Int",
		password:"String",
		updated_at:"timestamptz"
	},
	user_min_fields:{
		created_at:"timestamptz",
		email:"String",
		id:"Int",
		password:"String",
		updated_at:"timestamptz"
	},
	user_mutation_response:{
		affected_rows:"Int",
		returning:"user"
	},
	user_stddev_fields:{
		id:"Float"
	},
	user_stddev_pop_fields:{
		id:"Float"
	},
	user_stddev_samp_fields:{
		id:"Float"
	},
	user_sum_fields:{
		id:"Int"
	},
	user_var_pop_fields:{
		id:"Float"
	},
	user_var_samp_fields:{
		id:"Float"
	},
	user_variance_fields:{
		id:"Float"
	}
}